### PR TITLE
Tests cleanup - extra everything

### PR DESCRIPTION
**Pull request by redhog**
Had to merge in the other two pull requests into this one.

This one fixes all bugs that fails tests apart from test-compatibility (as usual).

### CODE REVIEW

**Comment by geowurster** [comment]
@redhog I added some things:

* Logging in `core.py` and `cli.py`
* Removed libais and Python3 from the Travis configfile so we can get CI rolling again

I tested this agains the NewlineJSON changes and tested GPSD with the new NLJ against benthos and nothing broke so on Monday can we step through merging this, releasing NewlineJSON, and releasing an updated GPSD format?  Would be nice to at least pull this into master so we can have continuous integration again, which should let us fix some other stuff as well.

**Comment by redhog** [comment]
Ping @geowurster Merge time?

**Comment by geowurster** [comment]
Maybe wait until we figure out how we're going to reprocess everything?  Would be a bummer to merge this and the raster sampling branch in Benthos only to discover that they broke a bunch of stuff that needs to be fixed before we can re-parse.

**Comment by redhog** [comment]
This is the branch I'm using in practice right now...

**Pull request merged**
